FROM node:22-alpine AS app


WORKDIR /app

RUN addgroup -S appuser && adduser -S appuser -G appuser

COPY package*.json /app/
RUN npm ci

COPY . .

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 5173

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
