FROM node:22-alpine AS app

WORKDIR /app

RUN addgroup -S appuser && adduser -S appuser -G appuser

COPY package*.json ./

RUN chown -R appuser:appuser /app

USER appuser

RUN npm ci

COPY --chown=appuser:appuser . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
