FROM node:22-alpine as app


WORKDIR /app

RUN addgroup -S appuser && adduser -S appuser -G appuser

COPY package*.json /app/
RUN npm ci

COPY . .

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
