services:
  db:
    container_name: cellim-viewer-db-prod
    image: postgres:17.4-alpine
    env_file:
      - ./backend/.env.prod
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - cellim-network
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    container_name: cellim-viewer-api-prod
    build:
      context: ./backend
      dockerfile: docker/dockerfile.prod
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - cellim-network
    depends_on:
      - db

  frontend:
    container_name: cellim-viewer-frontend-prod
    build:
      context: ./frontend
      dockerfile: docker/dockerfile.prod
    env_file:
      - ./backend/.env.prod
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - cellim-network
    depends_on:
      - api

  minio:
    container_name: cellim-viewer-minio-prod
    image: minio/minio:latest
    env_file:
      - ./backend/.env.prod
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - cellim-network
    volumes:
      - minio_data:/data

networks:
  cellim-network:
    driver: bridge

volumes:
  db_data:
  minio_data:
