services:
  db:
    container_name: cellim-viewer-db
    image: postgres:17.4-alpine
    env_file:
      - ./backend/.env.dev
    ports:
      - "5432:5432"
    restart: always
    networks:
      - cellim-network
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    container_name: cellim-viewer-api
    build:
      context: ./backend
      dockerfile: docker/dockerfile.dev
    env_file:
      - ./backend/.env.dev
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
        - action: rebuild
          path: ./backend/pyproject.toml
    restart: always
    networks:
      - cellim-network
    depends_on:
      - db

  web:
    container_name: cellim-viewer-web
    build:
      context: ./frontend
      dockerfile: docker/dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app/
        - action: rebuild
          path: ./frontend/package.json
    restart: always
    networks:
      - cellim-network
    depends_on:
      - api

  minio:
    container_name: cellim-viewer-minio
    image: minio/minio:latest
    env_file:
      - ./backend/.env.dev
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - cellim-network
    volumes:
      - minio_data:/data

  adminer:
    container_name: cellim-viewer-adminer
    image: adminer:latest
    env_file:
      - ./backend/.env.dev
    ports:
      - "8080:8080"
    restart: always
    networks:
      - cellim-network
    depends_on:
      - db

networks:
  cellim-network:
    driver: bridge

volumes:
  db_data:
  minio_data:
