services:
  db:
    container_name: cellim-viewer-db-dev
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.example
    restart: always
    networks:
      - cellim-network
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    container_name: cellim-viewer-api-dev
    build:
      context: ./backend
      dockerfile: docker/dockerfile.dev
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
        - action: rebuild
          path: ./backend/pyproject.toml
    restart: always
    networks:
      - cellim-network
    depends_on:
      - db

  frontend:
    container_name: cellim-viewer-frontend-dev
    build:
      context: ./frontend
      dockerfile: docker/dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app/
        - action: rebuild
          path: ./frontend/package.json
    restart: always
    networks:
      - cellim-network
    depends_on:
      - api

  minio:
    container_name: cellim-viewer-minio-dev
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./backend/.env.example
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - cellim-network
    volumes:
      - minio_data:/data

  adminer:
    container_name: cellim-viewer-adminer-dev
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    ports:
      - "8080:8080"
    restart: always
    networks:
      - cellim-network
    depends_on:
      - db

  # db-init:
  #   container_name: cellim-viewer-db-init-dev
  #   build:
  #     context: ./backend
  #     dockerfile: docker/dockerfile.dev
  #   env_file:
  #     - ./backend/.env.example
  #   command: >
  #     sh -c "
  #       echo 'Waiting for DB...' &&
  #       until pg_isready -h db -U postgres; do sleep 1; done &&
  #       sh scripts/migrate.sh upgrade head &&
  #       python -m app.database.seed.py
  #     "
  #   restart: "no"
  #   networks:
  #     - cellim-network
  #   depends_on:
  #     - db

  # nginx:
  #   container_name: cellim-viewer-nginx
  #   image: nginx:latest
  #   volumes:
  #     - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "6080:80"
  #     - "6443:443"
  #   restart: always
  #   networks:
  #     - cellim-network
  #   depends_on:
  #   - api
  #   - frontend

  # fix-perms:
  #   image: busybox
  #   volumes:
  #     - volseg_entries:/app/volseg-entries
  #   command: ["sh", "-c", "chown -R 1000:1000 /app/volseg-entries"]
  #   user: root
  #   entrypoint: ""
  #   networks:
  #     - cellim-network

networks:
  cellim-network:
    driver: bridge

volumes:
  db_data:
  minio_data:
  # volseg_entries:
