services:
  db:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cellim_viewer
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cellim-network
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: docker/dockerfile.prod
    ports:
      - "8000:8000"
    networks:
      - cellim-network
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/dockerfile.prod
    ports:
      - "80:80"
    networks:
      - cellim-network
    depends_on:
      - api
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data
    networks:
      - cellim-network
    restart: unless-stopped

networks:
  cellim-network:
    driver: bridge

volumes:
  db_data:
  minio_data:
