"""view order

Revision ID: 5e4d0efb4d42
Revises: 7998d084cd8a
Create Date: 2025-07-30 14:20:24.873582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4d0efb4d42'
down_revision: Union[str, Sequence[str], None] = '7998d084cd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('views', sa.Column('order_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('views', 'order_index')
    # ### end Alembic commands ###
