"""deleted_at

Revision ID: 7998d084cd8a
Revises: 6b9e0e8f3cda
Create Date: 2025-07-21 11:07:55.968379

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7998d084cd8a"
down_revision: Union[str, Sequence[str], None] = "6b9e0e8f3cda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entries", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column(
        "share_links", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("views", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column(
        "volseg_entries", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("volseg_entries", "deleted_at")
    op.drop_column("views", "deleted_at")
    op.drop_column("users", "deleted_at")
    op.drop_column("share_links", "deleted_at")
    op.drop_column("entries", "deleted_at")
    # ### end Alembic commands ###
