"""volseg entry snapshot_filepath

Revision ID: 3b2dbc8d837f
Revises: 854fd061e139
Create Date: 2025-07-09 08:58:04.335140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2dbc8d837f'
down_revision: Union[str, Sequence[str], None] = '854fd061e139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volseg_entries', sa.Column('snapshot_filepath', sa.String(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volseg_entries', 'snapshot_filepath')
    # ### end Alembic commands ###
