"""volseg entry annotations

Revision ID: 6b9e0e8f3cda
Revises: 3b2dbc8d837f
Create Date: 2025-07-09 09:22:03.090944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9e0e8f3cda'
down_revision: Union[str, Sequence[str], None] = '3b2dbc8d837f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volseg_entries', sa.Column('annotation_filepath', sa.String(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volseg_entries', 'annotation_filepath')
    # ### end Alembic commands ###
