// This file is auto-generated by @hey-api/openapi-ts

export const ApiKeyCreatedResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      examples: ["6cfec811-c860-4727-a0ba-a6482b8d29cc"],
    },
    created_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    updated_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    name: {
      type: "string",
    },
    prefix: {
      type: "string",
    },
    expires_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
    last_used_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
    key: {
      type: "string",
    },
  },
  type: "object",
  required: [
    "id",
    "created_at",
    "updated_at",
    "name",
    "prefix",
    "expires_at",
    "last_used_at",
    "key",
  ],
} as const;

export const ApiKeyResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      examples: ["6cfec811-c860-4727-a0ba-a6482b8d29cc"],
    },
    created_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    updated_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    name: {
      type: "string",
    },
    prefix: {
      type: "string",
    },
    expires_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
    last_used_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: [
    "id",
    "created_at",
    "updated_at",
    "name",
    "prefix",
    "expires_at",
    "last_used_at",
  ],
} as const;

export const Body_entries_upload_cvsxSchema = {
  properties: {
    dataset_file: {
      type: "string",
      format: "binary",
    },
  },
  type: "object",
  required: ["dataset_file"],
} as const;

export const CreateApiKeyRequestSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
    },
    expires_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["name"],
} as const;

export const EntryResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      examples: ["6cfec811-c860-4727-a0ba-a6482b8d29cc"],
    },
    created_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    updated_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    name: {
      type: "string",
    },
    title: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    status: {
      $ref: "#/components/schemas/EntryStatus",
    },
    share_link: {
      $ref: "#/components/schemas/ShareLinkResponse",
    },
    size_bytes: {
      type: "integer",
    },
    error_message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: [
    "id",
    "created_at",
    "updated_at",
    "name",
    "title",
    "description",
    "status",
    "share_link",
    "size_bytes",
    "error_message",
  ],
} as const;

export const EntryStatusSchema = {
  type: "string",
  enum: ["pending", "processing", "completed", "failed"],
} as const;

export const EntryUpdateRequestSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
    },
    title: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 2047,
        },
        {
          type: "null",
        },
      ],
    },
  },
  additionalProperties: false,
  type: "object",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
    },
  },
  type: "object",
} as const;

export const HealthCheckResponseSchema = {
  properties: {
    api: {
      type: "string",
      enum: ["unknown", "healthy", "unhealthy"],
      default: "unknown",
    },
    database: {
      type: "string",
      enum: ["unknown", "healthy", "unhealthy"],
      default: "unknown",
    },
    storage: {
      type: "string",
      enum: ["unknown", "healthy", "unhealthy"],
      default: "unknown",
    },
  },
  type: "object",
} as const;

export const InternalBoxSegmentSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    segment_id: {
      type: "integer",
    },
    color: {
      type: "string",
    },
    opacity: {
      type: "number",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    tooltip: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "box",
      default: "box",
    },
    center: {
      prefixItems: [
        {
          type: "number",
        },
        {
          type: "number",
        },
        {
          type: "number",
        },
      ],
      type: "array",
      maxItems: 3,
      minItems: 3,
    },
    extent: {
      prefixItems: [
        {
          type: "number",
        },
        {
          type: "number",
        },
        {
          type: "number",
        },
      ],
      type: "array",
      maxItems: 3,
      minItems: 3,
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "timeframe_id",
    "segmentation_id",
    "segment_id",
    "color",
    "opacity",
    "label",
    "tooltip",
    "description",
    "center",
    "extent",
  ],
} as const;

export const InternalEllipsoidSegmentSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    segment_id: {
      type: "integer",
    },
    color: {
      type: "string",
    },
    opacity: {
      type: "number",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    tooltip: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "ellipsoid",
      default: "ellipsoid",
    },
    center: {
      prefixItems: [
        {
          type: "number",
        },
        {
          type: "number",
        },
        {
          type: "number",
        },
      ],
      type: "array",
      maxItems: 3,
      minItems: 3,
    },
    major_axis: {
      prefixItems: [
        {
          type: "number",
        },
        {
          type: "number",
        },
        {
          type: "number",
        },
      ],
      type: "array",
      maxItems: 3,
      minItems: 3,
    },
    minor_axis: {
      prefixItems: [
        {
          type: "number",
        },
        {
          type: "number",
        },
        {
          type: "number",
        },
      ],
      type: "array",
      maxItems: 3,
      minItems: 3,
    },
    radius: {
      anyOf: [
        {
          prefixItems: [
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
          ],
          type: "array",
          maxItems: 3,
          minItems: 3,
        },
        {
          type: "number",
        },
      ],
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "timeframe_id",
    "segmentation_id",
    "segment_id",
    "color",
    "opacity",
    "label",
    "tooltip",
    "description",
    "center",
    "major_axis",
    "minor_axis",
    "radius",
  ],
} as const;

export const InternalEntry_InputSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    details: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    source_db_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    source_db_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    assets_directory: {
      type: "string",
    },
    timeframes: {
      items: {
        $ref: "#/components/schemas/InternalTimeframe-Input",
      },
      type: "array",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["assets_directory", "timeframes"],
} as const;

export const InternalEntry_OutputSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    details: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    source_db_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    source_db_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    assets_directory: {
      type: "string",
    },
    timeframes: {
      items: {
        $ref: "#/components/schemas/InternalTimeframe-Output",
      },
      type: "array",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["assets_directory", "timeframes"],
} as const;

export const InternalGeometricSegmentationSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    color: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    opacity: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "geometric",
      default: "geometric",
    },
    segments: {
      items: {
        anyOf: [
          {
            $ref: "#/components/schemas/InternalMeshSegment",
          },
          {
            $ref: "#/components/schemas/InternalEllipsoidSegment",
          },
          {
            $ref: "#/components/schemas/InternalSphereSegment",
          },
          {
            $ref: "#/components/schemas/InternalBoxSegment",
          },
          {
            $ref: "#/components/schemas/InternalTubeSegment",
          },
        ],
      },
      type: "array",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["timeframe_id", "segmentation_id", "segments"],
} as const;

export const InternalGridSliceVolumeSchema = {
  properties: {
    source_filepath: {
      type: "string",
    },
    timeframe_id: {
      type: "integer",
    },
    channel_id: {
      type: "string",
    },
    color: {
      type: "string",
    },
    opacity: {
      type: "number",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "grid_slice",
      default: "grid_slice",
    },
    absolute_isovalue: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
    },
    relative_isovalue: {
      type: "number",
    },
    dimension: {
      type: "string",
      enum: ["x", "y", "z"],
    },
    absolute_index: {
      type: "integer",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "source_filepath",
    "timeframe_id",
    "channel_id",
    "color",
    "opacity",
    "label",
    "description",
    "absolute_isovalue",
    "relative_isovalue",
    "dimension",
    "absolute_index",
  ],
} as const;

export const InternalIsosurfaceVolumeSchema = {
  properties: {
    source_filepath: {
      type: "string",
    },
    timeframe_id: {
      type: "integer",
    },
    channel_id: {
      type: "string",
    },
    color: {
      type: "string",
    },
    opacity: {
      type: "number",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "isosurface",
      default: "isosurface",
    },
    absolute_isovalue: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
    },
    relative_isovalue: {
      type: "number",
    },
    show_faces: {
      type: "boolean",
    },
    show_wireframe: {
      type: "boolean",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "source_filepath",
    "timeframe_id",
    "channel_id",
    "color",
    "opacity",
    "label",
    "description",
    "absolute_isovalue",
    "relative_isovalue",
    "show_faces",
    "show_wireframe",
  ],
} as const;

export const InternalMeshSegmentSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    segment_id: {
      type: "integer",
    },
    color: {
      type: "string",
    },
    opacity: {
      type: "number",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    tooltip: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "mesh",
      default: "mesh",
    },
    instance: {
      anyOf: [
        {
          prefixItems: [
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
            {
              type: "number",
            },
          ],
          type: "array",
          maxItems: 16,
          minItems: 16,
        },
        {
          type: "null",
        },
      ],
    },
    vertices: {
      items: {
        type: "number",
      },
      type: "array",
      default: [],
    },
    indices: {
      items: {
        type: "integer",
      },
      type: "array",
      default: [],
    },
    triangle_groups: {
      items: {
        type: "integer",
      },
      type: "array",
      default: [],
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "timeframe_id",
    "segmentation_id",
    "segment_id",
    "color",
    "opacity",
    "label",
    "tooltip",
    "description",
  ],
} as const;

export const InternalMeshSegmentationSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    color: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    opacity: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "mesh",
      default: "mesh",
    },
    segments: {
      items: {
        $ref: "#/components/schemas/InternalMeshSegment",
      },
      type: "array",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["timeframe_id", "segmentation_id", "segments"],
} as const;

export const InternalSphereSegmentSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    segment_id: {
      type: "integer",
    },
    color: {
      type: "string",
    },
    opacity: {
      type: "number",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    tooltip: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "sphere",
      default: "sphere",
    },
    center: {
      prefixItems: [
        {
          type: "number",
        },
        {
          type: "number",
        },
        {
          type: "number",
        },
      ],
      type: "array",
      maxItems: 3,
      minItems: 3,
    },
    radius: {
      type: "number",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "timeframe_id",
    "segmentation_id",
    "segment_id",
    "color",
    "opacity",
    "label",
    "tooltip",
    "description",
    "center",
    "radius",
  ],
} as const;

export const InternalTimeframe_InputSchema = {
  properties: {
    timeframe_id: {
      type: "integer",
    },
    volumes: {
      items: {
        anyOf: [
          {
            $ref: "#/components/schemas/InternalIsosurfaceVolume",
          },
          {
            $ref: "#/components/schemas/InternalGridSliceVolume",
          },
        ],
      },
      type: "array",
    },
    segmentations: {
      items: {
        anyOf: [
          {
            $ref: "#/components/schemas/InternalVolumeSegmentation",
          },
          {
            $ref: "#/components/schemas/InternalMeshSegmentation",
          },
          {
            $ref: "#/components/schemas/InternalGeometricSegmentation",
          },
        ],
      },
      type: "array",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["timeframe_id", "volumes", "segmentations"],
} as const;

export const InternalTimeframe_OutputSchema = {
  properties: {
    timeframe_id: {
      type: "integer",
    },
    volumes: {
      items: {
        anyOf: [
          {
            $ref: "#/components/schemas/InternalIsosurfaceVolume",
          },
          {
            $ref: "#/components/schemas/InternalGridSliceVolume",
          },
        ],
      },
      type: "array",
    },
    segmentations: {
      items: {
        anyOf: [
          {
            $ref: "#/components/schemas/InternalVolumeSegmentation",
          },
          {
            $ref: "#/components/schemas/InternalMeshSegmentation",
          },
          {
            $ref: "#/components/schemas/InternalGeometricSegmentation",
          },
        ],
      },
      type: "array",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["timeframe_id", "volumes", "segmentations"],
} as const;

export const InternalTubeSegmentSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    segment_id: {
      type: "integer",
    },
    color: {
      type: "string",
    },
    opacity: {
      type: "number",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    tooltip: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "tube",
      default: "tube",
    },
    start: {
      prefixItems: [
        {
          type: "number",
        },
        {
          type: "number",
        },
        {
          type: "number",
        },
      ],
      type: "array",
      maxItems: 3,
      minItems: 3,
    },
    end: {
      prefixItems: [
        {
          type: "number",
        },
        {
          type: "number",
        },
        {
          type: "number",
        },
      ],
      type: "array",
      maxItems: 3,
      minItems: 3,
    },
    radius: {
      type: "number",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "timeframe_id",
    "segmentation_id",
    "segment_id",
    "color",
    "opacity",
    "label",
    "tooltip",
    "description",
    "start",
    "end",
    "radius",
  ],
} as const;

export const InternalVolumeSegmentSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    segment_id: {
      type: "integer",
    },
    color: {
      type: "string",
    },
    opacity: {
      type: "number",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    tooltip: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "volume",
      default: "volume",
    },
    channel_id: {
      type: "string",
    },
    absolute_isovalue: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
    },
    relative_isovalue: {
      type: "number",
    },
    show_faces: {
      type: "boolean",
    },
    show_wireframe: {
      type: "boolean",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "timeframe_id",
    "segmentation_id",
    "segment_id",
    "color",
    "opacity",
    "label",
    "tooltip",
    "description",
    "channel_id",
    "absolute_isovalue",
    "relative_isovalue",
    "show_faces",
    "show_wireframe",
  ],
} as const;

export const InternalVolumeSegmentationSchema = {
  properties: {
    source_filepath: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    timeframe_id: {
      type: "integer",
    },
    segmentation_id: {
      type: "string",
    },
    color: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    opacity: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
    },
    kind: {
      type: "string",
      const: "volume",
      default: "volume",
    },
    segments: {
      items: {
        $ref: "#/components/schemas/InternalVolumeSegment",
      },
      type: "array",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["timeframe_id", "segmentation_id", "segments"],
} as const;

export const PaginatedResponse_EntryResponse_Schema = {
  properties: {
    page: {
      type: "integer",
      minimum: 1,
    },
    per_page: {
      type: "integer",
      maximum: 100,
      minimum: 1,
    },
    total_pages: {
      type: "integer",
    },
    total_items: {
      type: "integer",
    },
    items: {
      items: {
        $ref: "#/components/schemas/EntryResponse",
      },
      type: "array",
    },
  },
  type: "object",
  required: ["page", "per_page", "total_pages", "total_items", "items"],
} as const;

export const ShareLinkResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      examples: ["6cfec811-c860-4727-a0ba-a6482b8d29cc"],
    },
    created_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    updated_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    is_active: {
      type: "boolean",
    },
  },
  type: "object",
  required: ["id", "created_at", "updated_at", "is_active"],
} as const;

export const ShareLinkUpdateRequestSchema = {
  properties: {
    is_active: {
      type: "boolean",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["is_active"],
} as const;

export const UserResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      examples: ["6cfec811-c860-4727-a0ba-a6482b8d29cc"],
    },
    created_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    updated_at: {
      type: "string",
      format: "date-time",
      examples: ["2025-04-24 09:46:15.895023+00:00"],
    },
    sub: {
      type: "string",
    },
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    email: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    storage_quota: {
      type: "integer",
    },
    storage_usage: {
      type: "integer",
    },
  },
  type: "object",
  required: [
    "id",
    "created_at",
    "updated_at",
    "sub",
    "name",
    "email",
    "storage_quota",
    "storage_usage",
  ],
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
    },
    msg: {
      type: "string",
    },
    type: {
      type: "string",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
} as const;
