// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from "./client";
import type {
  EntriesListPublicEntriesData,
  EntriesListPublicEntriesResponses,
  EntriesListPublicEntriesErrors,
  EntriesCreateEntryData,
  EntriesCreateEntryResponses,
  EntriesCreateEntryErrors,
  EntriesDeleteEntryData,
  EntriesDeleteEntryResponses,
  EntriesDeleteEntryErrors,
  EntriesGetEntryByIdData,
  EntriesGetEntryByIdResponses,
  EntriesGetEntryByIdErrors,
  EntriesUpdateEntryData,
  EntriesUpdateEntryResponses,
  EntriesUpdateEntryErrors,
  EntriesGetEntryByShareLinkData,
  EntriesGetEntryByShareLinkResponses,
  EntriesGetEntryByShareLinkErrors,
  EntriesGetEntryShareLinkData,
  EntriesGetEntryShareLinkResponses,
  EntriesGetEntryShareLinkErrors,
  EntriesGetEntryThumbnailViewData,
  EntriesGetEntryThumbnailViewResponses,
  EntriesGetEntryThumbnailViewErrors,
  ViewsListViewsForEntryData,
  ViewsListViewsForEntryResponses,
  ViewsListViewsForEntryErrors,
  ViewsCreateViewData,
  ViewsCreateViewResponses,
  ViewsCreateViewErrors,
  ViewsDeleteViewData,
  ViewsDeleteViewResponses,
  ViewsDeleteViewErrors,
  ViewsGetViewByIdData,
  ViewsGetViewByIdResponses,
  ViewsGetViewByIdErrors,
  ViewsUpdateViewData,
  ViewsUpdateViewResponses,
  ViewsUpdateViewErrors,
  ViewsGetViewSnapshotData,
  ViewsGetViewSnapshotResponses,
  ViewsGetViewSnapshotErrors,
  ViewsGetViewThumbnailImageData,
  ViewsGetViewThumbnailImageResponses,
  ViewsGetViewThumbnailImageErrors,
  MeListEntriesForUserData,
  MeListEntriesForUserResponses,
  MeListEntriesForUserErrors,
  MeListVolsegEntriesForUserData,
  MeListVolsegEntriesForUserResponses,
  MeListVolsegEntriesForUserErrors,
  ShareLinksGetShareLinkData,
  ShareLinksGetShareLinkResponses,
  ShareLinksGetShareLinkErrors,
  ShareLinksUpdateShareLinkData,
  ShareLinksUpdateShareLinkResponses,
  ShareLinksUpdateShareLinkErrors,
  AuthLoginUserData,
  AuthLoginUserResponses,
  AuthLoginUserErrors,
  AuthOidcCallbackData,
  AuthOidcCallbackResponses,
  AuthOidcCallbackErrors,
  AuthLogoutData,
  AuthLogoutResponses,
  AuthReadUsersMeData,
  AuthReadUsersMeResponses,
  AuthGetUsersTokenData,
  AuthGetUsersTokenResponses,
  AuthVerifyAuthData,
  AuthVerifyAuthResponses,
  AuthDemoLoginData,
  AuthDemoLoginResponses,
  TestUploadFileData,
  TestUploadFileResponses,
  TestUploadFileErrors,
  VolsegEntriesListPublicEntriesData,
  VolsegEntriesListPublicEntriesResponses,
  VolsegEntriesListPublicEntriesErrors,
  VolsegEntriesUploadEntryData,
  VolsegEntriesUploadEntryResponses,
  VolsegEntriesUploadEntryErrors,
  VolsegEntriesDeleteViewData,
  VolsegEntriesDeleteViewResponses,
  VolsegEntriesDeleteViewErrors,
  VolsegEntriesGetEntryByIdData,
  VolsegEntriesGetEntryByIdResponses,
  VolsegEntriesGetEntryByIdErrors,
  VolsegEntriesGetCvsxFileData,
  VolsegEntriesGetCvsxFileResponses,
  VolsegEntriesGetCvsxFileErrors,
} from "./types.gen";
import {
  zEntriesListPublicEntriesData,
  zEntriesListPublicEntriesResponse,
  zEntriesCreateEntryData,
  zEntriesCreateEntryResponse,
  zEntriesDeleteEntryData,
  zEntriesDeleteEntryResponse,
  zEntriesGetEntryByIdData,
  zEntriesGetEntryByIdResponse,
  zEntriesUpdateEntryData,
  zEntriesUpdateEntryResponse,
  zEntriesGetEntryByShareLinkData,
  zEntriesGetEntryByShareLinkResponse,
  zEntriesGetEntryShareLinkData,
  zEntriesGetEntryShareLinkResponse,
  zEntriesGetEntryThumbnailViewData,
  zEntriesGetEntryThumbnailViewResponse,
  zViewsListViewsForEntryData,
  zViewsListViewsForEntryResponse,
  zViewsCreateViewData,
  zViewsCreateViewResponse,
  zViewsDeleteViewData,
  zViewsDeleteViewResponse,
  zViewsGetViewByIdData,
  zViewsGetViewByIdResponse,
  zViewsUpdateViewData,
  zViewsUpdateViewResponse,
  zViewsGetViewSnapshotData,
  zViewsGetViewThumbnailImageData,
  zMeListEntriesForUserData,
  zMeListEntriesForUserResponse,
  zMeListVolsegEntriesForUserData,
  zMeListVolsegEntriesForUserResponse,
  zShareLinksGetShareLinkData,
  zShareLinksGetShareLinkResponse,
  zShareLinksUpdateShareLinkData,
  zShareLinksUpdateShareLinkResponse,
  zAuthLoginUserData,
  zAuthOidcCallbackData,
  zAuthLogoutData,
  zAuthReadUsersMeData,
  zAuthReadUsersMeResponse,
  zAuthGetUsersTokenData,
  zAuthGetUsersTokenResponse,
  zAuthVerifyAuthData,
  zAuthVerifyAuthResponse,
  zAuthDemoLoginData,
  zTestUploadFileData,
  zVolsegEntriesListPublicEntriesData,
  zVolsegEntriesListPublicEntriesResponse,
  zVolsegEntriesUploadEntryData,
  zVolsegEntriesUploadEntryResponse,
  zVolsegEntriesDeleteViewData,
  zVolsegEntriesDeleteViewResponse,
  zVolsegEntriesGetEntryByIdData,
  zVolsegEntriesGetEntryByIdResponse,
  zVolsegEntriesGetCvsxFileData,
} from "./zod.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List Public Entries
 */
export const entriesListPublicEntries = <ThrowOnError extends boolean = false>(
  options: Options<EntriesListPublicEntriesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    EntriesListPublicEntriesResponses,
    EntriesListPublicEntriesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEntriesListPublicEntriesData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zEntriesListPublicEntriesResponse.parseAsync(data);
    },
    url: "/api/v1/entries",
    ...options,
  });
};

/**
 * Create Entry
 */
export const entriesCreateEntry = <ThrowOnError extends boolean = false>(
  options: Options<EntriesCreateEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    EntriesCreateEntryResponses,
    EntriesCreateEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEntriesCreateEntryData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zEntriesCreateEntryResponse.parseAsync(data);
    },
    url: "/api/v1/entries",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Entry
 */
export const entriesDeleteEntry = <ThrowOnError extends boolean = false>(
  options: Options<EntriesDeleteEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    EntriesDeleteEntryResponses,
    EntriesDeleteEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEntriesDeleteEntryData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zEntriesDeleteEntryResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}",
    ...options,
  });
};

/**
 * Get Entry By Id
 */
export const entriesGetEntryById = <ThrowOnError extends boolean = false>(
  options: Options<EntriesGetEntryByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    EntriesGetEntryByIdResponses,
    EntriesGetEntryByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEntriesGetEntryByIdData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zEntriesGetEntryByIdResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}",
    ...options,
  });
};

/**
 * Update Entry
 */
export const entriesUpdateEntry = <ThrowOnError extends boolean = false>(
  options: Options<EntriesUpdateEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    EntriesUpdateEntryResponses,
    EntriesUpdateEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEntriesUpdateEntryData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zEntriesUpdateEntryResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Entry By Share Link
 */
export const entriesGetEntryByShareLink = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EntriesGetEntryByShareLinkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    EntriesGetEntryByShareLinkResponses,
    EntriesGetEntryByShareLinkErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEntriesGetEntryByShareLinkData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zEntriesGetEntryByShareLinkResponse.parseAsync(data);
    },
    url: "/api/v1/entries/share/{share_link_id}",
    ...options,
  });
};

/**
 * Get Entry Share Link
 */
export const entriesGetEntryShareLink = <ThrowOnError extends boolean = false>(
  options: Options<EntriesGetEntryShareLinkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    EntriesGetEntryShareLinkResponses,
    EntriesGetEntryShareLinkErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEntriesGetEntryShareLinkData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zEntriesGetEntryShareLinkResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/share_link",
    ...options,
  });
};

/**
 * Get Entry Thumbnail View
 */
export const entriesGetEntryThumbnailView = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EntriesGetEntryThumbnailViewData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    EntriesGetEntryThumbnailViewResponses,
    EntriesGetEntryThumbnailViewErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEntriesGetEntryThumbnailViewData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zEntriesGetEntryThumbnailViewResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/thumbnail",
    ...options,
  });
};

/**
 * List Views For Entry
 */
export const viewsListViewsForEntry = <ThrowOnError extends boolean = false>(
  options: Options<ViewsListViewsForEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ViewsListViewsForEntryResponses,
    ViewsListViewsForEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zViewsListViewsForEntryData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zViewsListViewsForEntryResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/views",
    ...options,
  });
};

/**
 * Create View
 */
export const viewsCreateView = <ThrowOnError extends boolean = false>(
  options: Options<ViewsCreateViewData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ViewsCreateViewResponses,
    ViewsCreateViewErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    requestValidator: async (data) => {
      return await zViewsCreateViewData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zViewsCreateViewResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/views",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Delete View
 */
export const viewsDeleteView = <ThrowOnError extends boolean = false>(
  options: Options<ViewsDeleteViewData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    ViewsDeleteViewResponses,
    ViewsDeleteViewErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zViewsDeleteViewData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zViewsDeleteViewResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/views/{view_id}",
    ...options,
  });
};

/**
 * Get View By Id
 */
export const viewsGetViewById = <ThrowOnError extends boolean = false>(
  options: Options<ViewsGetViewByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ViewsGetViewByIdResponses,
    ViewsGetViewByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zViewsGetViewByIdData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zViewsGetViewByIdResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/views/{view_id}",
    ...options,
  });
};

/**
 * Update View
 */
export const viewsUpdateView = <ThrowOnError extends boolean = false>(
  options: Options<ViewsUpdateViewData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    ViewsUpdateViewResponses,
    ViewsUpdateViewErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zViewsUpdateViewData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zViewsUpdateViewResponse.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/views/{view_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get View Snapshot
 */
export const viewsGetViewSnapshot = <ThrowOnError extends boolean = false>(
  options: Options<ViewsGetViewSnapshotData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ViewsGetViewSnapshotResponses,
    ViewsGetViewSnapshotErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zViewsGetViewSnapshotData.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/views/{view_id}/snapshot",
    ...options,
  });
};

/**
 * Get View Thumbnail Image
 */
export const viewsGetViewThumbnailImage = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ViewsGetViewThumbnailImageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ViewsGetViewThumbnailImageResponses,
    ViewsGetViewThumbnailImageErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zViewsGetViewThumbnailImageData.parseAsync(data);
    },
    url: "/api/v1/entries/{entry_id}/views/{view_id}/thumbnail",
    ...options,
  });
};

/**
 * List Entries For User
 */
export const meListEntriesForUser = <ThrowOnError extends boolean = false>(
  options: Options<MeListEntriesForUserData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    MeListEntriesForUserResponses,
    MeListEntriesForUserErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zMeListEntriesForUserData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zMeListEntriesForUserResponse.parseAsync(data);
    },
    url: "/api/v1/me/entries",
    ...options,
  });
};

/**
 * List Volseg Entries For User
 */
export const meListVolsegEntriesForUser = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MeListVolsegEntriesForUserData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    MeListVolsegEntriesForUserResponses,
    MeListVolsegEntriesForUserErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zMeListVolsegEntriesForUserData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zMeListVolsegEntriesForUserResponse.parseAsync(data);
    },
    url: "/api/v1/me/volseg",
    ...options,
  });
};

/**
 * Get Share Link
 */
export const shareLinksGetShareLink = <ThrowOnError extends boolean = false>(
  options: Options<ShareLinksGetShareLinkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ShareLinksGetShareLinkResponses,
    ShareLinksGetShareLinkErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zShareLinksGetShareLinkData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zShareLinksGetShareLinkResponse.parseAsync(data);
    },
    url: "/api/v1/share_links/{share_link_id}",
    ...options,
  });
};

/**
 * Update Share Link
 */
export const shareLinksUpdateShareLink = <ThrowOnError extends boolean = false>(
  options: Options<ShareLinksUpdateShareLinkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    ShareLinksUpdateShareLinkResponses,
    ShareLinksUpdateShareLinkErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zShareLinksUpdateShareLinkData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zShareLinksUpdateShareLinkResponse.parseAsync(data);
    },
    url: "/api/v1/share_links/{share_link_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Login User
 */
export const authLoginUser = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLoginUserData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthLoginUserResponses,
    AuthLoginUserErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAuthLoginUserData.parseAsync(data);
    },
    url: "/api/v1/auth/login",
    ...options,
  });
};

/**
 * Oidc Callback
 */
export const authOidcCallback = <ThrowOnError extends boolean = false>(
  options: Options<AuthOidcCallbackData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    AuthOidcCallbackResponses,
    AuthOidcCallbackErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAuthOidcCallbackData.parseAsync(data);
    },
    url: "/api/v1/auth/callback",
    ...options,
  });
};

/**
 * Logout
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    AuthLogoutResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAuthLogoutData.parseAsync(data);
    },
    url: "/api/v1/auth/logout",
    ...options,
  });
};

/**
 * Read Users Me
 */
export const authReadUsersMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthReadUsersMeData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthReadUsersMeResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAuthReadUsersMeData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zAuthReadUsersMeResponse.parseAsync(data);
    },
    url: "/api/v1/auth/me/user",
    ...options,
  });
};

/**
 * Get Users Token
 */
export const authGetUsersToken = <ThrowOnError extends boolean = false>(
  options?: Options<AuthGetUsersTokenData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthGetUsersTokenResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAuthGetUsersTokenData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zAuthGetUsersTokenResponse.parseAsync(data);
    },
    url: "/api/v1/auth/me/token",
    ...options,
  });
};

/**
 * Verify Auth
 */
export const authVerifyAuth = <ThrowOnError extends boolean = false>(
  options?: Options<AuthVerifyAuthData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthVerifyAuthResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAuthVerifyAuthData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zAuthVerifyAuthResponse.parseAsync(data);
    },
    url: "/api/v1/auth/verify",
    ...options,
  });
};

/**
 * Demo Login
 */
export const authDemoLogin = <ThrowOnError extends boolean = false>(
  options?: Options<AuthDemoLoginData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthDemoLoginResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAuthDemoLoginData.parseAsync(data);
    },
    url: "/api/v1/auth/demo-login",
    ...options,
  });
};

/**
 * Upload File
 */
export const testUploadFile = <ThrowOnError extends boolean = false>(
  options: Options<TestUploadFileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    TestUploadFileResponses,
    TestUploadFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    requestValidator: async (data) => {
      return await zTestUploadFileData.parseAsync(data);
    },
    url: "/api/v1/test/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * List Public Entries
 */
export const volsegEntriesListPublicEntries = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<VolsegEntriesListPublicEntriesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    VolsegEntriesListPublicEntriesResponses,
    VolsegEntriesListPublicEntriesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zVolsegEntriesListPublicEntriesData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zVolsegEntriesListPublicEntriesResponse.parseAsync(data);
    },
    url: "/api/v1/volseg",
    ...options,
  });
};

/**
 * Upload Entry
 */
export const volsegEntriesUploadEntry = <ThrowOnError extends boolean = false>(
  options: Options<VolsegEntriesUploadEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    VolsegEntriesUploadEntryResponses,
    VolsegEntriesUploadEntryErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    requestValidator: async (data) => {
      return await zVolsegEntriesUploadEntryData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zVolsegEntriesUploadEntryResponse.parseAsync(data);
    },
    url: "/api/v1/volseg",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Delete View
 */
export const volsegEntriesDeleteView = <ThrowOnError extends boolean = false>(
  options: Options<VolsegEntriesDeleteViewData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    VolsegEntriesDeleteViewResponses,
    VolsegEntriesDeleteViewErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zVolsegEntriesDeleteViewData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zVolsegEntriesDeleteViewResponse.parseAsync(data);
    },
    url: "/api/v1/volseg/{volseg_entry_id}",
    ...options,
  });
};

/**
 * Get Entry By Id
 */
export const volsegEntriesGetEntryById = <ThrowOnError extends boolean = false>(
  options: Options<VolsegEntriesGetEntryByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    VolsegEntriesGetEntryByIdResponses,
    VolsegEntriesGetEntryByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zVolsegEntriesGetEntryByIdData.parseAsync(data);
    },
    responseValidator: async (data) => {
      return await zVolsegEntriesGetEntryByIdResponse.parseAsync(data);
    },
    url: "/api/v1/volseg/{volseg_entry_id}",
    ...options,
  });
};

/**
 * Get Cvsx File
 */
export const volsegEntriesGetCvsxFile = <ThrowOnError extends boolean = false>(
  options: Options<VolsegEntriesGetCvsxFileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    VolsegEntriesGetCvsxFileResponses,
    VolsegEntriesGetCvsxFileErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zVolsegEntriesGetCvsxFileData.parseAsync(data);
    },
    url: "/api/v1/volseg/{volseg_entry_id}/file",
    ...options,
  });
};
