// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * ApiKeyCreatedResponse
 */
export type ApiKeyCreatedResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Name
   */
  name: string;
  /**
   * Prefix
   */
  prefix: string;
  /**
   * Expires At
   */
  expires_at: string | null;
  /**
   * Last Used At
   */
  last_used_at: string | null;
  /**
   * Key
   *
   * The raw API key. Only returned once upon creation.
   */
  key: string;
};

/**
 * ApiKeyResponse
 */
export type ApiKeyResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Name
   */
  name: string;
  /**
   * Prefix
   */
  prefix: string;
  /**
   * Expires At
   */
  expires_at: string | null;
  /**
   * Last Used At
   */
  last_used_at: string | null;
};

/**
 * Body_entries-upload_cvsx
 */
export type BodyEntriesUploadCvsx = {
  /**
   * Dataset File
   */
  dataset_file: Blob | File;
};

/**
 * CreateApiKeyRequest
 */
export type CreateApiKeyRequest = {
  /**
   * Name
   *
   * Friendly name for the key
   */
  name: string;
  /**
   * Expires At
   *
   * Optional expiration date
   */
  expires_at?: string | null;
};

/**
 * EntryResponse
 */
export type EntryResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Name
   */
  name: string;
  /**
   * Title
   */
  title: string | null;
  /**
   * Description
   */
  description: string | null;
  status: EntryStatus;
  share_link: ShareLinkResponse;
  /**
   * Size Bytes
   */
  size_bytes: number;
  /**
   * Error Message
   */
  error_message: string | null;
};

/**
 * EntryStatus
 */
export type EntryStatus = "pending" | "processing" | "completed" | "failed";

/**
 * EntryUpdateRequest
 */
export type EntryUpdateRequest = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthCheckResponse
 */
export type HealthCheckResponse = {
  /**
   * Api
   */
  api?: "unknown" | "healthy" | "unhealthy";
  /**
   * Database
   */
  database?: "unknown" | "healthy" | "unhealthy";
  /**
   * Storage
   */
  storage?: "unknown" | "healthy" | "unhealthy";
};

/**
 * InternalBoxSegment
 */
export type InternalBoxSegment = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Segment Id
   */
  segment_id: number;
  /**
   * Color
   */
  color: string;
  /**
   * Opacity
   */
  opacity: number;
  /**
   * Label
   */
  label: string | null;
  /**
   * Tooltip
   */
  tooltip: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Kind
   */
  kind?: "box";
  /**
   * Center
   */
  center: [number, number, number];
  /**
   * Extent
   */
  extent: [number, number, number];
};

/**
 * InternalEllipsoidSegment
 */
export type InternalEllipsoidSegment = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Segment Id
   */
  segment_id: number;
  /**
   * Color
   */
  color: string;
  /**
   * Opacity
   */
  opacity: number;
  /**
   * Label
   */
  label: string | null;
  /**
   * Tooltip
   */
  tooltip: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Kind
   */
  kind?: "ellipsoid";
  /**
   * Center
   */
  center: [number, number, number];
  /**
   * Major Axis
   */
  major_axis: [number, number, number];
  /**
   * Minor Axis
   */
  minor_axis: [number, number, number];
  /**
   * Radius
   */
  radius: [number, number, number] | number;
};

/**
 * InternalEntry
 */
export type InternalEntryInput = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Details
   */
  details?: string | null;
  /**
   * Source Db Id
   */
  source_db_id?: string | null;
  /**
   * Source Db Name
   */
  source_db_name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Assets Directory
   */
  assets_directory: string;
  /**
   * Timeframes
   */
  timeframes: Array<InternalTimeframeInput>;
};

/**
 * InternalEntry
 */
export type InternalEntryOutput = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Details
   */
  details?: string | null;
  /**
   * Source Db Id
   */
  source_db_id?: string | null;
  /**
   * Source Db Name
   */
  source_db_name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Assets Directory
   */
  assets_directory: string;
  /**
   * Timeframes
   */
  timeframes: Array<InternalTimeframeOutput>;
};

/**
 * InternalGeometricSegmentation
 */
export type InternalGeometricSegmentation = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Opacity
   */
  opacity?: number | null;
  /**
   * Kind
   */
  kind?: "geometric";
  /**
   * Segments
   */
  segments: Array<
    | InternalMeshSegment
    | InternalEllipsoidSegment
    | InternalSphereSegment
    | InternalBoxSegment
    | InternalTubeSegment
  >;
};

/**
 * InternalGridSliceVolume
 */
export type InternalGridSliceVolume = {
  /**
   * Source Filepath
   */
  source_filepath: string;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Channel Id
   */
  channel_id: string;
  /**
   * Color
   */
  color: string;
  /**
   * Opacity
   */
  opacity: number;
  /**
   * Label
   */
  label: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Kind
   */
  kind?: "grid_slice";
  /**
   * Absolute Isovalue
   */
  absolute_isovalue: number | null;
  /**
   * Relative Isovalue
   */
  relative_isovalue: number;
  /**
   * Dimension
   */
  dimension: "x" | "y" | "z";
  /**
   * Absolute Index
   */
  absolute_index: number;
};

/**
 * InternalIsosurfaceVolume
 */
export type InternalIsosurfaceVolume = {
  /**
   * Source Filepath
   */
  source_filepath: string;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Channel Id
   */
  channel_id: string;
  /**
   * Color
   */
  color: string;
  /**
   * Opacity
   */
  opacity: number;
  /**
   * Label
   */
  label: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Kind
   */
  kind?: "isosurface";
  /**
   * Absolute Isovalue
   */
  absolute_isovalue: number | null;
  /**
   * Relative Isovalue
   */
  relative_isovalue: number;
  /**
   * Show Faces
   */
  show_faces: boolean;
  /**
   * Show Wireframe
   */
  show_wireframe: boolean;
};

/**
 * InternalMeshSegment
 */
export type InternalMeshSegment = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Segment Id
   */
  segment_id: number;
  /**
   * Color
   */
  color: string;
  /**
   * Opacity
   */
  opacity: number;
  /**
   * Label
   */
  label: string | null;
  /**
   * Tooltip
   */
  tooltip: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Kind
   */
  kind?: "mesh";
  /**
   * Instance
   */
  instance?:
    | [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
      ]
    | null;
  /**
   * Vertices
   */
  vertices?: Array<number>;
  /**
   * Indices
   */
  indices?: Array<number>;
  /**
   * Triangle Groups
   */
  triangle_groups?: Array<number>;
};

/**
 * InternalMeshSegmentation
 */
export type InternalMeshSegmentation = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Opacity
   */
  opacity?: number | null;
  /**
   * Kind
   */
  kind?: "mesh";
  /**
   * Segments
   */
  segments: Array<InternalMeshSegment>;
};

/**
 * InternalSphereSegment
 */
export type InternalSphereSegment = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Segment Id
   */
  segment_id: number;
  /**
   * Color
   */
  color: string;
  /**
   * Opacity
   */
  opacity: number;
  /**
   * Label
   */
  label: string | null;
  /**
   * Tooltip
   */
  tooltip: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Kind
   */
  kind?: "sphere";
  /**
   * Center
   */
  center: [number, number, number];
  /**
   * Radius
   */
  radius: number;
};

/**
 * InternalTimeframe
 */
export type InternalTimeframeInput = {
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Volumes
   */
  volumes: Array<InternalIsosurfaceVolume | InternalGridSliceVolume>;
  /**
   * Segmentations
   */
  segmentations: Array<
    | InternalVolumeSegmentation
    | InternalMeshSegmentation
    | InternalGeometricSegmentation
  >;
};

/**
 * InternalTimeframe
 */
export type InternalTimeframeOutput = {
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Volumes
   */
  volumes: Array<InternalIsosurfaceVolume | InternalGridSliceVolume>;
  /**
   * Segmentations
   */
  segmentations: Array<
    | InternalVolumeSegmentation
    | InternalMeshSegmentation
    | InternalGeometricSegmentation
  >;
};

/**
 * InternalTubeSegment
 */
export type InternalTubeSegment = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Segment Id
   */
  segment_id: number;
  /**
   * Color
   */
  color: string;
  /**
   * Opacity
   */
  opacity: number;
  /**
   * Label
   */
  label: string | null;
  /**
   * Tooltip
   */
  tooltip: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Kind
   */
  kind?: "tube";
  /**
   * Start
   */
  start: [number, number, number];
  /**
   * End
   */
  end: [number, number, number];
  /**
   * Radius
   */
  radius: number;
};

/**
 * InternalVolumeSegment
 */
export type InternalVolumeSegment = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Segment Id
   */
  segment_id: number;
  /**
   * Color
   */
  color: string;
  /**
   * Opacity
   */
  opacity: number;
  /**
   * Label
   */
  label: string | null;
  /**
   * Tooltip
   */
  tooltip: string | null;
  /**
   * Description
   */
  description: string | null;
  /**
   * Kind
   */
  kind?: "volume";
  /**
   * Channel Id
   */
  channel_id: string;
  /**
   * Absolute Isovalue
   */
  absolute_isovalue: number | null;
  /**
   * Relative Isovalue
   */
  relative_isovalue: number;
  /**
   * Show Faces
   */
  show_faces: boolean;
  /**
   * Show Wireframe
   */
  show_wireframe: boolean;
};

/**
 * InternalVolumeSegmentation
 */
export type InternalVolumeSegmentation = {
  /**
   * Source Filepath
   */
  source_filepath?: string | null;
  /**
   * Timeframe Id
   */
  timeframe_id: number;
  /**
   * Segmentation Id
   */
  segmentation_id: string;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Opacity
   */
  opacity?: number | null;
  /**
   * Kind
   */
  kind?: "volume";
  /**
   * Segments
   */
  segments: Array<InternalVolumeSegment>;
};

/**
 * PaginatedResponse[EntryResponse]
 */
export type PaginatedResponseEntryResponse = {
  /**
   * Page
   */
  page: number;
  /**
   * Per Page
   */
  per_page: number;
  /**
   * Total Pages
   */
  total_pages: number;
  /**
   * Total Items
   */
  total_items: number;
  /**
   * Items
   */
  items: Array<EntryResponse>;
};

/**
 * ShareLinkResponse
 */
export type ShareLinkResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Is Active
   */
  is_active: boolean;
};

/**
 * ShareLinkUpdateRequest
 */
export type ShareLinkUpdateRequest = {
  /**
   * Is Active
   *
   * Whether the share link is active
   */
  is_active: boolean;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Sub
   */
  sub: string;
  /**
   * Name
   */
  name: string | null;
  /**
   * Email
   */
  email: string | null;
  /**
   * Storage Quota
   */
  storage_quota: number;
  /**
   * Storage Usage
   */
  storage_usage: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type HealthCheckHealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health_check";
};

export type HealthCheckHealthCheckErrors = {
  /**
   * Service is unhealthy - one or more dependencies are unavailable
   */
  503: HealthCheckResponse;
};

export type HealthCheckHealthCheckError =
  HealthCheckHealthCheckErrors[keyof HealthCheckHealthCheckErrors];

export type HealthCheckHealthCheckResponses = {
  /**
   * Service is healthy
   */
  200: HealthCheckResponse;
};

export type HealthCheckHealthCheckResponse =
  HealthCheckHealthCheckResponses[keyof HealthCheckHealthCheckResponses];

export type ApiKeysListApiKeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/api-keys";
};

export type ApiKeysListApiKeysResponses = {
  /**
   * Response Api Keys-List Api Keys
   *
   * Successful Response
   */
  200: Array<ApiKeyResponse>;
};

export type ApiKeysListApiKeysResponse =
  ApiKeysListApiKeysResponses[keyof ApiKeysListApiKeysResponses];

export type ApiKeysCreateApiKeyData = {
  body: CreateApiKeyRequest;
  path?: never;
  query?: never;
  url: "/api/v1/api-keys";
};

export type ApiKeysCreateApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiKeysCreateApiKeyError =
  ApiKeysCreateApiKeyErrors[keyof ApiKeysCreateApiKeyErrors];

export type ApiKeysCreateApiKeyResponses = {
  /**
   * Successful Response
   */
  201: ApiKeyCreatedResponse;
};

export type ApiKeysCreateApiKeyResponse =
  ApiKeysCreateApiKeyResponses[keyof ApiKeysCreateApiKeyResponses];

export type ApiKeysRevokeApiKeyData = {
  body?: never;
  path: {
    /**
     * Key Id
     */
    key_id: string;
  };
  query?: never;
  url: "/api/v1/api-keys/{key_id}";
};

export type ApiKeysRevokeApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiKeysRevokeApiKeyError =
  ApiKeysRevokeApiKeyErrors[keyof ApiKeysRevokeApiKeyErrors];

export type ApiKeysRevokeApiKeyResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ApiKeysRevokeApiKeyResponse =
  ApiKeysRevokeApiKeyResponses[keyof ApiKeysRevokeApiKeyResponses];

export type AuthLoginUserData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Redirect
     */
    redirect?: string;
  };
  url: "/api/v1/auth/login";
};

export type AuthLoginUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthLoginUserError = AuthLoginUserErrors[keyof AuthLoginUserErrors];

export type AuthLoginUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthOidcCallbackData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Code
     */
    code: string;
    /**
     * State
     */
    state: string;
  };
  url: "/api/v1/auth/callback";
};

export type AuthOidcCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthOidcCallbackError =
  AuthOidcCallbackErrors[keyof AuthOidcCallbackErrors];

export type AuthOidcCallbackResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type AuthLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthGetUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/user";
};

export type AuthGetUserResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type AuthGetUserResponse =
  AuthGetUserResponses[keyof AuthGetUserResponses];

export type AuthVerifyAuthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/verify";
};

export type AuthVerifyAuthResponses = {
  /**
   * Response Auth-Verify Auth
   *
   * Successful Response
   */
  200: boolean;
};

export type AuthVerifyAuthResponse =
  AuthVerifyAuthResponses[keyof AuthVerifyAuthResponses];

export type AuthDemoLoginData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Redirect
     */
    redirect?: string;
  };
  url: "/api/v1/auth/demo-login";
};

export type AuthDemoLoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthDemoLoginError = AuthDemoLoginErrors[keyof AuthDemoLoginErrors];

export type AuthDemoLoginResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EntriesListUserEntriesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Per Page
     */
    per_page?: number;
    /**
     * Sort By
     */
    sort_by?: "name" | "size_bytes" | "created_at" | "status";
    /**
     * Sort Order
     */
    sort_order?: "asc" | "desc";
  };
  url: "/api/v1/entries";
};

export type EntriesListUserEntriesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesListUserEntriesError =
  EntriesListUserEntriesErrors[keyof EntriesListUserEntriesErrors];

export type EntriesListUserEntriesResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponseEntryResponse;
};

export type EntriesListUserEntriesResponse =
  EntriesListUserEntriesResponses[keyof EntriesListUserEntriesResponses];

export type EntriesUploadCvsxData = {
  body: BodyEntriesUploadCvsx;
  path?: never;
  query?: {
    /**
     * Lattice To Mesh
     *
     * Transform lattice to mesh (True) or volume (False)
     */
    lattice_to_mesh?: boolean;
  };
  url: "/api/v1/entries";
};

export type EntriesUploadCvsxErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesUploadCvsxError =
  EntriesUploadCvsxErrors[keyof EntriesUploadCvsxErrors];

export type EntriesUploadCvsxResponses = {
  /**
   * Successful Response
   */
  201: EntryResponse;
};

export type EntriesUploadCvsxResponse =
  EntriesUploadCvsxResponses[keyof EntriesUploadCvsxResponses];

export type EntriesDeleteEntryData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: never;
  url: "/api/v1/entries/{entry_id}";
};

export type EntriesDeleteEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesDeleteEntryError =
  EntriesDeleteEntryErrors[keyof EntriesDeleteEntryErrors];

export type EntriesDeleteEntryResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EntriesGetEntryByIdData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: never;
  url: "/api/v1/entries/{entry_id}";
};

export type EntriesGetEntryByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesGetEntryByIdError =
  EntriesGetEntryByIdErrors[keyof EntriesGetEntryByIdErrors];

export type EntriesGetEntryByIdResponses = {
  /**
   * Successful Response
   */
  200: EntryResponse;
};

export type EntriesGetEntryByIdResponse =
  EntriesGetEntryByIdResponses[keyof EntriesGetEntryByIdResponses];

export type EntriesUpdateEntryData = {
  body: EntryUpdateRequest;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: never;
  url: "/api/v1/entries/{entry_id}";
};

export type EntriesUpdateEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesUpdateEntryError =
  EntriesUpdateEntryErrors[keyof EntriesUpdateEntryErrors];

export type EntriesUpdateEntryResponses = {
  /**
   * Successful Response
   */
  200: EntryResponse;
};

export type EntriesUpdateEntryResponse =
  EntriesUpdateEntryResponses[keyof EntriesUpdateEntryResponses];

export type EntriesGetEntryShareLinkData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: never;
  url: "/api/v1/entries/{entry_id}/share-link";
};

export type EntriesGetEntryShareLinkErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesGetEntryShareLinkError =
  EntriesGetEntryShareLinkErrors[keyof EntriesGetEntryShareLinkErrors];

export type EntriesGetEntryShareLinkResponses = {
  /**
   * Successful Response
   */
  200: ShareLinkResponse;
};

export type EntriesGetEntryShareLinkResponse =
  EntriesGetEntryShareLinkResponses[keyof EntriesGetEntryShareLinkResponses];

export type EntriesGetEntryModelData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: never;
  url: "/api/v1/entries/{entry_id}/model";
};

export type EntriesGetEntryModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesGetEntryModelError =
  EntriesGetEntryModelErrors[keyof EntriesGetEntryModelErrors];

export type EntriesGetEntryModelResponses = {
  /**
   * Successful Response
   */
  200: InternalEntryOutput;
};

export type EntriesGetEntryModelResponse =
  EntriesGetEntryModelResponses[keyof EntriesGetEntryModelResponses];

export type EntriesUpdateEntryModelData = {
  /**
   * Internal Model JSON
   */
  body: InternalEntryInput;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: never;
  url: "/api/v1/entries/{entry_id}/model";
};

export type EntriesUpdateEntryModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesUpdateEntryModelError =
  EntriesUpdateEntryModelErrors[keyof EntriesUpdateEntryModelErrors];

export type EntriesUpdateEntryModelResponses = {
  /**
   * Successful Response
   */
  200: InternalEntryOutput;
};

export type EntriesUpdateEntryModelResponse =
  EntriesUpdateEntryModelResponses[keyof EntriesUpdateEntryModelResponses];

export type EntriesDownloadData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: {
    /**
     * Format Type
     */
    format_type?: "mvsx" | "mvstory";
  };
  url: "/api/v1/entries/{entry_id}/download";
};

export type EntriesDownloadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesDownloadError =
  EntriesDownloadErrors[keyof EntriesDownloadErrors];

export type EntriesDownloadResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ShareLinksGetEntryByShareLinkData = {
  body?: never;
  path: {
    /**
     * Share Link ID
     */
    share_link_id: string;
  };
  query?: never;
  url: "/api/v1/share_links/{share_link_id}/entry";
};

export type ShareLinksGetEntryByShareLinkErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ShareLinksGetEntryByShareLinkError =
  ShareLinksGetEntryByShareLinkErrors[keyof ShareLinksGetEntryByShareLinkErrors];

export type ShareLinksGetEntryByShareLinkResponses = {
  /**
   * Successful Response
   */
  200: EntryResponse;
};

export type ShareLinksGetEntryByShareLinkResponse =
  ShareLinksGetEntryByShareLinkResponses[keyof ShareLinksGetEntryByShareLinkResponses];

export type ShareLinksGetEntryModelData = {
  body?: never;
  path: {
    /**
     * Share Link ID
     */
    share_link_id: string;
  };
  query?: never;
  url: "/api/v1/share_links/{share_link_id}/model";
};

export type ShareLinksGetEntryModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ShareLinksGetEntryModelError =
  ShareLinksGetEntryModelErrors[keyof ShareLinksGetEntryModelErrors];

export type ShareLinksGetEntryModelResponses = {
  /**
   * Successful Response
   */
  200: InternalEntryOutput;
};

export type ShareLinksGetEntryModelResponse =
  ShareLinksGetEntryModelResponses[keyof ShareLinksGetEntryModelResponses];

export type ShareLinksDownloadData = {
  body?: never;
  path: {
    /**
     * Share Link ID
     */
    share_link_id: string;
  };
  query?: {
    /**
     * Format Type
     */
    format_type?: "mvsx" | "mvstory";
  };
  url: "/api/v1/share_links/{share_link_id}/download";
};

export type ShareLinksDownloadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ShareLinksDownloadError =
  ShareLinksDownloadErrors[keyof ShareLinksDownloadErrors];

export type ShareLinksDownloadResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ShareLinksUpdateShareLinkData = {
  body: ShareLinkUpdateRequest;
  path: {
    /**
     * Share Link ID
     */
    share_link_id: string;
  };
  query?: never;
  url: "/api/v1/share_links/{share_link_id}";
};

export type ShareLinksUpdateShareLinkErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ShareLinksUpdateShareLinkError =
  ShareLinksUpdateShareLinkErrors[keyof ShareLinksUpdateShareLinkErrors];

export type ShareLinksUpdateShareLinkResponses = {
  /**
   * Successful Response
   */
  200: ShareLinkResponse;
};

export type ShareLinksUpdateShareLinkResponse =
  ShareLinksUpdateShareLinkResponses[keyof ShareLinksUpdateShareLinkResponses];
