// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_test-upload_file
 */
export type BodyTestUploadFile = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * Body_volseg entries-upload_entry
 */
export type BodyVolsegEntriesUploadEntry = {
  /**
   * Name
   */
  name: string;
  /**
   * Is Public
   */
  is_public: boolean;
  /**
   * Cvsx File
   */
  cvsx_file: Blob | File;
};

/**
 * EntryCreateRequest
 */
export type EntryCreateRequest = {
  /**
   * Volseg Entry Id
   */
  volseg_entry_id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Is Public
   */
  is_public?: boolean | null;
};

/**
 * EntryResponse
 */
export type EntryResponse = {
  /**
   * Response Model
   */
  response_model?: string;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Thumbnail Url
   */
  thumbnail_url?: string | null;
  /**
   * Is Public
   */
  is_public: boolean;
  /**
   * Volseg Entry Id
   */
  volseg_entry_id: string;
};

/**
 * EntryUpdateRequest
 */
export type EntryUpdateRequest = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Is Public
   */
  is_public?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * PaginatedResponse[EntryResponse]
 */
export type PaginatedResponseEntryResponse = {
  /**
   * Response Model
   */
  response_model?: string;
  /**
   * Page
   */
  page: number;
  /**
   * Per Page
   */
  per_page: number;
  /**
   * Total Pages
   */
  total_pages: number;
  /**
   * Total Items
   */
  total_items: number;
  /**
   * Items
   */
  items: Array<EntryResponse>;
};

/**
 * SearchQueryParams
 */
export type SearchQueryParams = {
  /**
   * Search Term
   * Keywords to search by in entry titles and descriptions.
   */
  search_term?: string | null;
  /**
   * Page
   */
  page?: number;
  /**
   * Per Page
   */
  per_page?: number;
};

/**
 * ShareLinkResponse
 */
export type ShareLinkResponse = {
  /**
   * Response Model
   */
  response_model?: string;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Entry Id
   */
  entry_id: string;
  /**
   * Is Editable
   */
  is_editable: boolean;
  /**
   * Is Active
   */
  is_active: boolean;
};

/**
 * ShareLinkUpdateRequest
 */
export type ShareLinkUpdateRequest = {
  /**
   * Is Editable
   */
  is_editable?: boolean | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Response Model
   */
  response_model?: string;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Openid
   */
  openid: string;
  /**
   * Email
   */
  email: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * ViewCreateRequest
 */
export type ViewCreateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Snapshot Json
   * Mol* state file (.molj file)
   */
  snapshot_json?: (Blob | File) | null;
  /**
   * Thumbnail Image
   * Thumbnail image for view
   */
  thumbnail_image?: (Blob | File) | null;
  /**
   * Is Thumbnail
   */
  is_thumbnail: boolean;
};

/**
 * ViewResponse
 */
export type ViewResponse = {
  /**
   * Response Model
   */
  response_model?: string;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Entry Id
   */
  entry_id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string | null;
  /**
   * Thumbnail Url
   */
  thumbnail_url: string | null;
  /**
   * Snapshot Url
   */
  snapshot_url: string | null;
  /**
   * Is Thumbnail
   */
  is_thumbnail: boolean;
};

/**
 * ViewUpdateRequest
 */
export type ViewUpdateRequest = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Is Thumbnail
   */
  is_thumbnail?: boolean | null;
};

/**
 * VolsegEntryResponse
 */
export type VolsegEntryResponse = {
  /**
   * Response Model
   */
  response_model?: string;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Name
   */
  name: string;
  /**
   * Is Public
   */
  is_public: boolean;
  /**
   * Cvsx Filepath
   */
  cvsx_filepath: string | null;
};

export type EntriesListPublicEntriesData = {
  body?: never;
  path?: never;
  query: {
    search_query: SearchQueryParams;
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries";
};

export type EntriesListPublicEntriesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesListPublicEntriesError =
  EntriesListPublicEntriesErrors[keyof EntriesListPublicEntriesErrors];

export type EntriesListPublicEntriesResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponseEntryResponse;
};

export type EntriesListPublicEntriesResponse =
  EntriesListPublicEntriesResponses[keyof EntriesListPublicEntriesResponses];

export type EntriesCreateEntryData = {
  body: EntryCreateRequest;
  path?: never;
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries";
};

export type EntriesCreateEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesCreateEntryError =
  EntriesCreateEntryErrors[keyof EntriesCreateEntryErrors];

export type EntriesCreateEntryResponses = {
  /**
   * Successful Response
   */
  201: EntryResponse;
};

export type EntriesCreateEntryResponse =
  EntriesCreateEntryResponses[keyof EntriesCreateEntryResponses];

export type EntriesDeleteEntryData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}";
};

export type EntriesDeleteEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesDeleteEntryError =
  EntriesDeleteEntryErrors[keyof EntriesDeleteEntryErrors];

export type EntriesDeleteEntryResponses = {
  /**
   * Response Entries-Delete Entry
   * Successful Response
   */
  200: string;
};

export type EntriesDeleteEntryResponse =
  EntriesDeleteEntryResponses[keyof EntriesDeleteEntryResponses];

export type EntriesGetEntryByIdData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}";
};

export type EntriesGetEntryByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesGetEntryByIdError =
  EntriesGetEntryByIdErrors[keyof EntriesGetEntryByIdErrors];

export type EntriesGetEntryByIdResponses = {
  /**
   * Successful Response
   */
  200: EntryResponse;
};

export type EntriesGetEntryByIdResponse =
  EntriesGetEntryByIdResponses[keyof EntriesGetEntryByIdResponses];

export type EntriesUpdateEntryData = {
  body: EntryUpdateRequest;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}";
};

export type EntriesUpdateEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesUpdateEntryError =
  EntriesUpdateEntryErrors[keyof EntriesUpdateEntryErrors];

export type EntriesUpdateEntryResponses = {
  /**
   * Successful Response
   */
  200: EntryResponse;
};

export type EntriesUpdateEntryResponse =
  EntriesUpdateEntryResponses[keyof EntriesUpdateEntryResponses];

export type EntriesGetEntryByShareLinkData = {
  body?: never;
  path: {
    /**
     * Share Link
     */
    share_link_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/share/{share_link_id}";
};

export type EntriesGetEntryByShareLinkErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesGetEntryByShareLinkError =
  EntriesGetEntryByShareLinkErrors[keyof EntriesGetEntryByShareLinkErrors];

export type EntriesGetEntryByShareLinkResponses = {
  /**
   * Successful Response
   */
  200: EntryResponse;
};

export type EntriesGetEntryByShareLinkResponse =
  EntriesGetEntryByShareLinkResponses[keyof EntriesGetEntryByShareLinkResponses];

export type EntriesGetEntryShareLinkData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/share_link";
};

export type EntriesGetEntryShareLinkErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesGetEntryShareLinkError =
  EntriesGetEntryShareLinkErrors[keyof EntriesGetEntryShareLinkErrors];

export type EntriesGetEntryShareLinkResponses = {
  /**
   * Successful Response
   */
  200: ShareLinkResponse;
};

export type EntriesGetEntryShareLinkResponse =
  EntriesGetEntryShareLinkResponses[keyof EntriesGetEntryShareLinkResponses];

export type EntriesGetEntryThumbnailViewData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/thumbnail";
};

export type EntriesGetEntryThumbnailViewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EntriesGetEntryThumbnailViewError =
  EntriesGetEntryThumbnailViewErrors[keyof EntriesGetEntryThumbnailViewErrors];

export type EntriesGetEntryThumbnailViewResponses = {
  /**
   * Successful Response
   */
  200: ViewResponse;
};

export type EntriesGetEntryThumbnailViewResponse =
  EntriesGetEntryThumbnailViewResponses[keyof EntriesGetEntryThumbnailViewResponses];

export type ViewsListViewsForEntryData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/views";
};

export type ViewsListViewsForEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ViewsListViewsForEntryError =
  ViewsListViewsForEntryErrors[keyof ViewsListViewsForEntryErrors];

export type ViewsListViewsForEntryResponses = {
  /**
   * Response Views-List Views For Entry
   * Successful Response
   */
  200: Array<ViewResponse>;
};

export type ViewsListViewsForEntryResponse =
  ViewsListViewsForEntryResponses[keyof ViewsListViewsForEntryResponses];

export type ViewsCreateViewData = {
  body: ViewCreateRequest;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/views";
};

export type ViewsCreateViewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ViewsCreateViewError =
  ViewsCreateViewErrors[keyof ViewsCreateViewErrors];

export type ViewsCreateViewResponses = {
  /**
   * Successful Response
   */
  201: ViewResponse;
};

export type ViewsCreateViewResponse =
  ViewsCreateViewResponses[keyof ViewsCreateViewResponses];

export type ViewsDeleteViewData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
    /**
     * View ID
     */
    view_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/views/{view_id}";
};

export type ViewsDeleteViewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ViewsDeleteViewError =
  ViewsDeleteViewErrors[keyof ViewsDeleteViewErrors];

export type ViewsDeleteViewResponses = {
  /**
   * Response Views-Delete View
   * Successful Response
   */
  200: string;
};

export type ViewsDeleteViewResponse =
  ViewsDeleteViewResponses[keyof ViewsDeleteViewResponses];

export type ViewsGetViewByIdData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
    /**
     * View ID
     */
    view_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/views/{view_id}";
};

export type ViewsGetViewByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ViewsGetViewByIdError =
  ViewsGetViewByIdErrors[keyof ViewsGetViewByIdErrors];

export type ViewsGetViewByIdResponses = {
  /**
   * Successful Response
   */
  200: ViewResponse;
};

export type ViewsGetViewByIdResponse =
  ViewsGetViewByIdResponses[keyof ViewsGetViewByIdResponses];

export type ViewsUpdateViewData = {
  body: ViewUpdateRequest;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
    /**
     * View ID
     */
    view_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/views/{view_id}";
};

export type ViewsUpdateViewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ViewsUpdateViewError =
  ViewsUpdateViewErrors[keyof ViewsUpdateViewErrors];

export type ViewsUpdateViewResponses = {
  /**
   * Successful Response
   */
  200: ViewResponse;
};

export type ViewsUpdateViewResponse =
  ViewsUpdateViewResponses[keyof ViewsUpdateViewResponses];

export type ViewsGetViewSnapshotData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
    /**
     * View ID
     */
    view_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/views/{view_id}/snapshot";
};

export type ViewsGetViewSnapshotErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ViewsGetViewSnapshotError =
  ViewsGetViewSnapshotErrors[keyof ViewsGetViewSnapshotErrors];

export type ViewsGetViewSnapshotResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ViewsGetViewThumbnailImageData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    entry_id: string;
    /**
     * View ID
     */
    view_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/entries/{entry_id}/views/{view_id}/thumbnail";
};

export type ViewsGetViewThumbnailImageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ViewsGetViewThumbnailImageError =
  ViewsGetViewThumbnailImageErrors[keyof ViewsGetViewThumbnailImageErrors];

export type ViewsGetViewThumbnailImageResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MeListEntriesForUserData = {
  body?: never;
  path?: never;
  query: {
    search_query: SearchQueryParams;
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/me/entries";
};

export type MeListEntriesForUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MeListEntriesForUserError =
  MeListEntriesForUserErrors[keyof MeListEntriesForUserErrors];

export type MeListEntriesForUserResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponseEntryResponse;
};

export type MeListEntriesForUserResponse =
  MeListEntriesForUserResponses[keyof MeListEntriesForUserResponses];

export type MeListVolsegEntriesForUserData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/me/volseg";
};

export type MeListVolsegEntriesForUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MeListVolsegEntriesForUserError =
  MeListVolsegEntriesForUserErrors[keyof MeListVolsegEntriesForUserErrors];

export type MeListVolsegEntriesForUserResponses = {
  /**
   * Response Me-List Volseg Entries For User
   * Successful Response
   */
  200: Array<VolsegEntryResponse>;
};

export type MeListVolsegEntriesForUserResponse =
  MeListVolsegEntriesForUserResponses[keyof MeListVolsegEntriesForUserResponses];

export type ShareLinksGetShareLinkData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    share_link_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/share_links/{share_link_id}";
};

export type ShareLinksGetShareLinkErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ShareLinksGetShareLinkError =
  ShareLinksGetShareLinkErrors[keyof ShareLinksGetShareLinkErrors];

export type ShareLinksGetShareLinkResponses = {
  /**
   * Successful Response
   */
  200: ShareLinkResponse;
};

export type ShareLinksGetShareLinkResponse =
  ShareLinksGetShareLinkResponses[keyof ShareLinksGetShareLinkResponses];

export type ShareLinksUpdateShareLinkData = {
  body: ShareLinkUpdateRequest;
  path: {
    /**
     * Entry ID
     */
    share_link_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/share_links/{share_link_id}";
};

export type ShareLinksUpdateShareLinkErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ShareLinksUpdateShareLinkError =
  ShareLinksUpdateShareLinkErrors[keyof ShareLinksUpdateShareLinkErrors];

export type ShareLinksUpdateShareLinkResponses = {
  /**
   * Successful Response
   */
  200: ShareLinkResponse;
};

export type ShareLinksUpdateShareLinkResponse =
  ShareLinksUpdateShareLinkResponses[keyof ShareLinksUpdateShareLinkResponses];

export type AuthLoginUserData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Redirect
     */
    redirect?: string;
  };
  url: "/api/v1/auth/login";
};

export type AuthLoginUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthLoginUserError = AuthLoginUserErrors[keyof AuthLoginUserErrors];

export type AuthLoginUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthOidcCallbackData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Code
     */
    code: string;
    /**
     * State
     */
    state: string;
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/auth/callback";
};

export type AuthOidcCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthOidcCallbackError =
  AuthOidcCallbackErrors[keyof AuthOidcCallbackErrors];

export type AuthOidcCallbackResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type AuthLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthReadUsersMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me/user";
};

export type AuthReadUsersMeResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type AuthReadUsersMeResponse =
  AuthReadUsersMeResponses[keyof AuthReadUsersMeResponses];

export type AuthGetUsersTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me/token";
};

export type AuthGetUsersTokenResponses = {
  /**
   * Response Auth-Get Users Token
   * Successful Response
   */
  200: string | null;
};

export type AuthGetUsersTokenResponse =
  AuthGetUsersTokenResponses[keyof AuthGetUsersTokenResponses];

export type AuthVerifyAuthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/verify";
};

export type AuthVerifyAuthResponses = {
  /**
   * Response Auth-Verify Auth
   * Successful Response
   */
  200: boolean;
};

export type AuthVerifyAuthResponse =
  AuthVerifyAuthResponses[keyof AuthVerifyAuthResponses];

export type AuthDemoLoginData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/demo-login";
};

export type AuthDemoLoginResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type TestUploadFileData = {
  body: BodyTestUploadFile;
  path?: never;
  query?: never;
  url: "/api/v1/test/upload";
};

export type TestUploadFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TestUploadFileError =
  TestUploadFileErrors[keyof TestUploadFileErrors];

export type TestUploadFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VolsegEntriesListPublicEntriesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/volseg";
};

export type VolsegEntriesListPublicEntriesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VolsegEntriesListPublicEntriesError =
  VolsegEntriesListPublicEntriesErrors[keyof VolsegEntriesListPublicEntriesErrors];

export type VolsegEntriesListPublicEntriesResponses = {
  /**
   * Response Volseg Entries-List Public Entries
   * Successful Response
   */
  200: Array<VolsegEntryResponse>;
};

export type VolsegEntriesListPublicEntriesResponse =
  VolsegEntriesListPublicEntriesResponses[keyof VolsegEntriesListPublicEntriesResponses];

export type VolsegEntriesUploadEntryData = {
  body: BodyVolsegEntriesUploadEntry;
  path?: never;
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/volseg";
};

export type VolsegEntriesUploadEntryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VolsegEntriesUploadEntryError =
  VolsegEntriesUploadEntryErrors[keyof VolsegEntriesUploadEntryErrors];

export type VolsegEntriesUploadEntryResponses = {
  /**
   * Successful Response
   */
  200: VolsegEntryResponse;
};

export type VolsegEntriesUploadEntryResponse =
  VolsegEntriesUploadEntryResponses[keyof VolsegEntriesUploadEntryResponses];

export type VolsegEntriesDeleteViewData = {
  body?: never;
  path: {
    /**
     * Volseg Entry ID
     */
    volseg_entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/volseg/{volseg_entry_id}";
};

export type VolsegEntriesDeleteViewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VolsegEntriesDeleteViewError =
  VolsegEntriesDeleteViewErrors[keyof VolsegEntriesDeleteViewErrors];

export type VolsegEntriesDeleteViewResponses = {
  /**
   * Response Volseg Entries-Delete View
   * Successful Response
   */
  200: string;
};

export type VolsegEntriesDeleteViewResponse =
  VolsegEntriesDeleteViewResponses[keyof VolsegEntriesDeleteViewResponses];

export type VolsegEntriesGetEntryByIdData = {
  body?: never;
  path: {
    /**
     * Volseg Entry ID
     */
    volseg_entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/volseg/{volseg_entry_id}";
};

export type VolsegEntriesGetEntryByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VolsegEntriesGetEntryByIdError =
  VolsegEntriesGetEntryByIdErrors[keyof VolsegEntriesGetEntryByIdErrors];

export type VolsegEntriesGetEntryByIdResponses = {
  /**
   * Successful Response
   */
  200: VolsegEntryResponse;
};

export type VolsegEntriesGetEntryByIdResponse =
  VolsegEntriesGetEntryByIdResponses[keyof VolsegEntriesGetEntryByIdResponses];

export type VolsegEntriesGetCvsxFileData = {
  body?: never;
  path: {
    /**
     * Entry ID
     */
    volseg_entry_id: string;
  };
  query?: {
    /**
     * Url
     */
    url?: string;
  };
  url: "/api/v1/volseg/{volseg_entry_id}/file";
};

export type VolsegEntriesGetCvsxFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VolsegEntriesGetCvsxFileError =
  VolsegEntriesGetCvsxFileErrors[keyof VolsegEntriesGetCvsxFileErrors];

export type VolsegEntriesGetCvsxFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};
