// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zBodyVolsegEntriesUploadEntry = z.object({
  name: z.string().max(255),
  is_public: z.boolean(),
  cvsx_file: z.string(),
});

export const zEntryCreateRequest = z.object({
  volseg_entry_id: z.string().uuid(),
  name: z.string().min(1).max(255),
  description: z.union([z.string(), z.null()]).optional(),
  is_public: z.union([z.boolean(), z.null()]).optional(),
});

export const zEntryResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]).optional(),
  thumbnail_url: z.union([z.string(), z.null()]).optional(),
  is_public: z.boolean(),
  volseg_entry_id: z.string().uuid(),
});

export const zEntryUpdateRequest = z.object({
  name: z.union([z.string().min(1).max(255), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  is_public: z.union([z.boolean(), z.null()]).optional(),
});

export const zValidationError = z.object({
  loc: z.array(z.unknown()),
  msg: z.string(),
  type: z.string(),
});

export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zPaginatedResponseEntryResponse = z.object({
  response_model: z.string().optional().default(""),
  page: z.number().int().gte(1),
  per_page: z.number().int().gte(1).lte(100),
  total_pages: z.number().int(),
  total_items: z.number().int(),
  items: z.array(zEntryResponse),
});

export const zShareLinkResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  entry_id: z.string().uuid(),
  is_editable: z.boolean(),
  is_active: z.boolean(),
});

export const zShareLinkUpdateRequest = z.object({
  is_editable: z.union([z.boolean(), z.null()]).optional(),
  is_active: z.union([z.boolean(), z.null()]).optional(),
});

export const zUploadFileRequest = z.object({
  file: z.string(),
});

export const zUserResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  openid: z.string(),
  email: z.string(),
});

export const zViewCreateRequest = z.object({
  name: z.string().min(1).max(255),
  description: z.union([z.string().max(255), z.null()]).optional(),
  snapshot_json: z.union([z.string(), z.null()]).optional(),
  thumbnail_image: z.union([z.string(), z.null()]).optional(),
  is_thumbnail: z.boolean(),
});

export const zViewResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  entry_id: z.string().uuid(),
  name: z.string().max(255),
  description: z.union([z.string(), z.null()]),
  thumbnail_url: z.union([z.string().max(2083), z.null()]),
  snapshot_url: z.union([z.string().max(2083), z.null()]),
  is_thumbnail: z.boolean(),
});

export const zViewUpdateRequest = z.object({
  name: z.union([z.string().min(1).max(255), z.null()]).optional(),
  description: z.union([z.string().max(255), z.null()]).optional(),
  is_thumbnail: z.union([z.boolean(), z.null()]).optional(),
});

export const zVolsegEntryResponse = z.object({
  response_model: z.string().optional().default(""),
  id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  name: z.string().max(255),
  is_public: z.boolean(),
  cvsx_filepath: z.union([z.string().max(2083), z.null()]),
});

export const zEntriesListPublicEntriesResponse =
  zPaginatedResponseEntryResponse;

export const zEntriesCreateEntryResponse = zEntryResponse;

export const zEntriesDeleteEntryResponse = z.string().uuid();

export const zEntriesGetEntryByIdResponse = zEntryResponse;

export const zEntriesUpdateEntryResponse = zEntryResponse;

export const zEntriesGetEntryByShareLinkResponse = zEntryResponse;

export const zEntriesGetEntryShareLinkResponse = zShareLinkResponse;

export const zEntriesGetEntryThumbnailViewResponse = zViewResponse;

export const zViewsListViewsForEntryResponse = z.array(zViewResponse);

export const zViewsCreateViewResponse = zViewResponse;

export const zViewsDeleteViewResponse = z.string().uuid();

export const zViewsGetViewByIdResponse = zViewResponse;

export const zViewsUpdateViewResponse = zViewResponse;

export const zMeListEntriesForUserResponse = zPaginatedResponseEntryResponse;

export const zMeListVolsegEntriesForUserResponse =
  z.array(zVolsegEntryResponse);

export const zShareLinksGetShareLinkResponse = zShareLinkResponse;

export const zShareLinksUpdateShareLinkResponse = zShareLinkResponse;

export const zAuthReadUsersMeResponse = zUserResponse;

export const zAuthGetUsersTokenResponse = z.union([z.string(), z.null()]);

export const zAuthVerifyAuthResponse = z.boolean();

export const zVolsegEntriesListPublicEntriesResponse =
  z.array(zVolsegEntryResponse);

export const zVolsegEntriesUploadEntryResponse = zVolsegEntryResponse;

export const zVolsegEntriesDeleteViewResponse = z.string().uuid();

export const zVolsegEntriesGetEntryByIdResponse = zVolsegEntryResponse;
