// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * ApiKeyCreatedResponse
 */
export const zApiKeyCreatedResponse = z.object({
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  name: z.string(),
  prefix: z.string(),
  expires_at: z.union([z.iso.datetime(), z.null()]),
  last_used_at: z.union([z.iso.datetime(), z.null()]),
  key: z.string(),
});

/**
 * ApiKeyResponse
 */
export const zApiKeyResponse = z.object({
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  name: z.string(),
  prefix: z.string(),
  expires_at: z.union([z.iso.datetime(), z.null()]),
  last_used_at: z.union([z.iso.datetime(), z.null()]),
});

/**
 * Body_entries-upload_cvsx
 */
export const zBodyEntriesUploadCvsx = z.object({
  dataset_file: z.string(),
});

/**
 * CreateApiKeyRequest
 */
export const zCreateApiKeyRequest = z.object({
  name: z.string().min(1).max(255),
  expires_at: z.optional(z.union([z.iso.datetime(), z.null()])),
});

/**
 * EntryStatus
 */
export const zEntryStatus = z.enum([
  "pending",
  "processing",
  "completed",
  "failed",
]);

/**
 * EntryUpdateRequest
 */
export const zEntryUpdateRequest = z.object({
  name: z.optional(z.union([z.string().max(255), z.null()])),
  title: z.optional(z.union([z.string().max(255), z.null()])),
  description: z.optional(z.union([z.string().max(2047), z.null()])),
});

/**
 * HealthCheckResponse
 */
export const zHealthCheckResponse = z.object({
  api: z.optional(z.enum(["unknown", "healthy", "unhealthy"])),
  database: z.optional(z.enum(["unknown", "healthy", "unhealthy"])),
  storage: z.optional(z.enum(["unknown", "healthy", "unhealthy"])),
});

/**
 * InternalBoxSegment
 */
export const zInternalBoxSegment = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  segment_id: z.int(),
  color: z.string(),
  opacity: z.number(),
  label: z.union([z.string(), z.null()]),
  tooltip: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  kind: z.optional(z.literal("box")).default("box"),
  center: z.tuple([z.number(), z.number(), z.number()]),
  extent: z.tuple([z.number(), z.number(), z.number()]),
});

/**
 * InternalEllipsoidSegment
 */
export const zInternalEllipsoidSegment = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  segment_id: z.int(),
  color: z.string(),
  opacity: z.number(),
  label: z.union([z.string(), z.null()]),
  tooltip: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  kind: z.optional(z.literal("ellipsoid")).default("ellipsoid"),
  center: z.tuple([z.number(), z.number(), z.number()]),
  major_axis: z.tuple([z.number(), z.number(), z.number()]),
  minor_axis: z.tuple([z.number(), z.number(), z.number()]),
  radius: z.union([z.tuple([z.number(), z.number(), z.number()]), z.number()]),
});

/**
 * InternalGridSliceVolume
 */
export const zInternalGridSliceVolume = z.object({
  source_filepath: z.string(),
  timeframe_id: z.int(),
  channel_id: z.string(),
  color: z.string(),
  opacity: z.number(),
  label: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  kind: z.optional(z.literal("grid_slice")).default("grid_slice"),
  absolute_isovalue: z.union([z.number(), z.null()]),
  relative_isovalue: z.number(),
  dimension: z.enum(["x", "y", "z"]),
  absolute_index: z.int(),
});

/**
 * InternalIsosurfaceVolume
 */
export const zInternalIsosurfaceVolume = z.object({
  source_filepath: z.string(),
  timeframe_id: z.int(),
  channel_id: z.string(),
  color: z.string(),
  opacity: z.number(),
  label: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  kind: z.optional(z.literal("isosurface")).default("isosurface"),
  absolute_isovalue: z.union([z.number(), z.null()]),
  relative_isovalue: z.number(),
  show_faces: z.boolean(),
  show_wireframe: z.boolean(),
});

/**
 * InternalMeshSegment
 */
export const zInternalMeshSegment = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  segment_id: z.int(),
  color: z.string(),
  opacity: z.number(),
  label: z.union([z.string(), z.null()]),
  tooltip: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  kind: z.optional(z.literal("mesh")).default("mesh"),
  instance: z.optional(
    z.union([
      z.tuple([
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
        z.number(),
      ]),
      z.null(),
    ]),
  ),
  vertices: z.optional(z.array(z.number())).default([]),
  indices: z.optional(z.array(z.int())).default([]),
  triangle_groups: z.optional(z.array(z.int())).default([]),
});

/**
 * InternalMeshSegmentation
 */
export const zInternalMeshSegmentation = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  color: z.optional(z.union([z.string(), z.null()])),
  opacity: z.optional(z.union([z.number(), z.null()])),
  kind: z.optional(z.literal("mesh")).default("mesh"),
  segments: z.array(zInternalMeshSegment),
});

/**
 * InternalSphereSegment
 */
export const zInternalSphereSegment = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  segment_id: z.int(),
  color: z.string(),
  opacity: z.number(),
  label: z.union([z.string(), z.null()]),
  tooltip: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  kind: z.optional(z.literal("sphere")).default("sphere"),
  center: z.tuple([z.number(), z.number(), z.number()]),
  radius: z.number(),
});

/**
 * InternalTubeSegment
 */
export const zInternalTubeSegment = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  segment_id: z.int(),
  color: z.string(),
  opacity: z.number(),
  label: z.union([z.string(), z.null()]),
  tooltip: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  kind: z.optional(z.literal("tube")).default("tube"),
  start: z.tuple([z.number(), z.number(), z.number()]),
  end: z.tuple([z.number(), z.number(), z.number()]),
  radius: z.number(),
});

/**
 * InternalGeometricSegmentation
 */
export const zInternalGeometricSegmentation = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  color: z.optional(z.union([z.string(), z.null()])),
  opacity: z.optional(z.union([z.number(), z.null()])),
  kind: z.optional(z.literal("geometric")).default("geometric"),
  segments: z.array(
    z.union([
      zInternalMeshSegment,
      zInternalEllipsoidSegment,
      zInternalSphereSegment,
      zInternalBoxSegment,
      zInternalTubeSegment,
    ]),
  ),
});

/**
 * InternalVolumeSegment
 */
export const zInternalVolumeSegment = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  segment_id: z.int(),
  color: z.string(),
  opacity: z.number(),
  label: z.union([z.string(), z.null()]),
  tooltip: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  kind: z.optional(z.literal("volume")).default("volume"),
  channel_id: z.string(),
  absolute_isovalue: z.union([z.number(), z.null()]),
  relative_isovalue: z.number(),
  show_faces: z.boolean(),
  show_wireframe: z.boolean(),
});

/**
 * InternalVolumeSegmentation
 */
export const zInternalVolumeSegmentation = z.object({
  source_filepath: z.optional(z.union([z.string(), z.null()])),
  timeframe_id: z.int(),
  segmentation_id: z.string(),
  color: z.optional(z.union([z.string(), z.null()])),
  opacity: z.optional(z.union([z.number(), z.null()])),
  kind: z.optional(z.literal("volume")).default("volume"),
  segments: z.array(zInternalVolumeSegment),
});

/**
 * InternalTimeframe
 */
export const zInternalTimeframeInput = z.object({
  timeframe_id: z.int(),
  volumes: z.array(
    z.union([zInternalIsosurfaceVolume, zInternalGridSliceVolume]),
  ),
  segmentations: z.array(
    z.union([
      zInternalVolumeSegmentation,
      zInternalMeshSegmentation,
      zInternalGeometricSegmentation,
    ]),
  ),
});

/**
 * InternalEntry
 */
export const zInternalEntryInput = z.object({
  name: z.optional(z.union([z.string(), z.null()])),
  details: z.optional(z.union([z.string(), z.null()])),
  source_db_id: z.optional(z.union([z.string(), z.null()])),
  source_db_name: z.optional(z.union([z.string(), z.null()])),
  description: z.optional(z.union([z.string(), z.null()])),
  url: z.optional(z.union([z.string(), z.null()])),
  assets_directory: z.string(),
  timeframes: z.array(zInternalTimeframeInput),
});

/**
 * InternalTimeframe
 */
export const zInternalTimeframeOutput = z.object({
  timeframe_id: z.int(),
  volumes: z.array(
    z.union([zInternalIsosurfaceVolume, zInternalGridSliceVolume]),
  ),
  segmentations: z.array(
    z.union([
      zInternalVolumeSegmentation,
      zInternalMeshSegmentation,
      zInternalGeometricSegmentation,
    ]),
  ),
});

/**
 * InternalEntry
 */
export const zInternalEntryOutput = z.object({
  name: z.optional(z.union([z.string(), z.null()])),
  details: z.optional(z.union([z.string(), z.null()])),
  source_db_id: z.optional(z.union([z.string(), z.null()])),
  source_db_name: z.optional(z.union([z.string(), z.null()])),
  description: z.optional(z.union([z.string(), z.null()])),
  url: z.optional(z.union([z.string(), z.null()])),
  assets_directory: z.string(),
  timeframes: z.array(zInternalTimeframeOutput),
});

/**
 * ShareLinkResponse
 */
export const zShareLinkResponse = z.object({
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  is_active: z.boolean(),
});

/**
 * EntryResponse
 */
export const zEntryResponse = z.object({
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  name: z.string(),
  title: z.union([z.string(), z.null()]),
  description: z.union([z.string(), z.null()]),
  status: zEntryStatus,
  share_link: zShareLinkResponse,
  size_bytes: z.int(),
  error_message: z.union([z.string(), z.null()]),
});

/**
 * PaginatedResponse[EntryResponse]
 */
export const zPaginatedResponseEntryResponse = z.object({
  page: z.int().gte(1),
  per_page: z.int().gte(1).lte(100),
  total_pages: z.int(),
  total_items: z.int(),
  items: z.array(zEntryResponse),
});

/**
 * ShareLinkUpdateRequest
 */
export const zShareLinkUpdateRequest = z.object({
  is_active: z.boolean(),
});

/**
 * UserResponse
 */
export const zUserResponse = z.object({
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  sub: z.string(),
  name: z.union([z.string(), z.null()]),
  email: z.union([z.string(), z.null()]),
  storage_quota: z.int(),
  storage_usage: z.int(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

export const zHealthCheckHealthCheckData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Service is healthy
 */
export const zHealthCheckHealthCheckResponse = zHealthCheckResponse;

export const zApiKeysListApiKeysData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Api Keys-List Api Keys
 *
 * Successful Response
 */
export const zApiKeysListApiKeysResponse = z.array(zApiKeyResponse);

export const zApiKeysCreateApiKeyData = z.object({
  body: zCreateApiKeyRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zApiKeysCreateApiKeyResponse = zApiKeyCreatedResponse;

export const zApiKeysRevokeApiKeyData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    key_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zApiKeysRevokeApiKeyResponse = z.void();

export const zAuthLoginUserData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      redirect: z.optional(z.string()).default("/dashboard"),
    }),
  ),
});

export const zAuthOidcCallbackData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    code: z.string(),
    state: z.string(),
  }),
});

export const zAuthLogoutData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAuthGetUserData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zAuthGetUserResponse = zUserResponse;

export const zAuthVerifyAuthData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Auth-Verify Auth
 *
 * Successful Response
 */
export const zAuthVerifyAuthResponse = z.boolean();

export const zAuthDemoLoginData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      redirect: z.optional(z.string()).default("/dashboard"),
    }),
  ),
});

export const zEntriesListUserEntriesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.int().gte(1)).default(1),
      per_page: z.optional(z.int().gte(1).lte(100)).default(10),
      sort_by: z.optional(
        z.enum(["name", "size_bytes", "created_at", "status"]),
      ),
      sort_order: z.optional(z.enum(["asc", "desc"])),
    }),
  ),
});

/**
 * Successful Response
 */
export const zEntriesListUserEntriesResponse = zPaginatedResponseEntryResponse;

export const zEntriesUploadCvsxData = z.object({
  body: zBodyEntriesUploadCvsx,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      lattice_to_mesh: z.optional(z.boolean()).default(true),
    }),
  ),
});

/**
 * Successful Response
 */
export const zEntriesUploadCvsxResponse = zEntryResponse;

export const zEntriesDeleteEntryData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    entry_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zEntriesGetEntryByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    entry_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zEntriesGetEntryByIdResponse = zEntryResponse;

export const zEntriesUpdateEntryData = z.object({
  body: zEntryUpdateRequest,
  path: z.object({
    entry_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zEntriesUpdateEntryResponse = zEntryResponse;

export const zEntriesGetEntryShareLinkData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    entry_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zEntriesGetEntryShareLinkResponse = zShareLinkResponse;

export const zEntriesGetEntryModelData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    entry_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zEntriesGetEntryModelResponse = zInternalEntryOutput;

export const zEntriesUpdateEntryModelData = z.object({
  body: zInternalEntryInput,
  path: z.object({
    entry_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zEntriesUpdateEntryModelResponse = zInternalEntryOutput;

export const zEntriesDownloadData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    entry_id: z.uuid(),
  }),
  query: z.optional(
    z.object({
      format_type: z.optional(z.enum(["mvsx", "mvstory"])),
    }),
  ),
});

export const zShareLinksGetEntryByShareLinkData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    share_link_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zShareLinksGetEntryByShareLinkResponse = zEntryResponse;

export const zShareLinksGetEntryModelData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    share_link_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zShareLinksGetEntryModelResponse = zInternalEntryOutput;

export const zShareLinksDownloadData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    share_link_id: z.uuid(),
  }),
  query: z.optional(
    z.object({
      format_type: z.optional(z.enum(["mvsx", "mvstory"])),
    }),
  ),
});

export const zShareLinksUpdateShareLinkData = z.object({
  body: zShareLinkUpdateRequest,
  path: z.object({
    share_link_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zShareLinksUpdateShareLinkResponse = zShareLinkResponse;
